config/routes.rb
Crit::Application.routes.draw do

  mount CommunityEngine::Engine => "/"

  #get  '/' => 'base#site_index', :as => :home

  resources :achievements
  resources :player_registrations
  resources :intake_survey
  resources :game_systems
  resources :properties
  resources :characters
  resources :games
  resources :events do
    resources :slots
  end
  resources :characters
  resources :products
  resources :system_categories

  post '/logout' => 'sessions#destroy', :as => :logout_button

  get  '/game_systems/:id/migrate/:system_category_id' => 'game_systems#migrate', :as => :game_system_migrate
  get  '/system_categories/search/:game_system_id' => 'system_categories#index', :as => :system_category_search
  get  '/system_categories/new_game' => 'system_categories#new_game', :as => :system_categories_new_game


  get  '/system_categories/:id/pick_profile_photo' => 'system_categories#pick_profile_photo', :as => :system_category_pick_profile_photo
  put  '/system_categories/:id/change_profile_photo' => 'system_categories#change_profile_photo', :as => :system_category_change_profile_photo
  get  '/system_categories/:id/bump_views' => 'system_categories#bump_views', :as => :system_category_bump_views
  get  '/system_categories/:id/product/search' => 'system_categories#product_search', :as => :system_category_product_search
  get  '/system_categories/:id/product/:product_id/add' => 'system_categories#product_add', :as => :system_category_product_add
  get  '/system_categories/:id/product/:product_id/remove' => 'system_categories#product_remove', :as => :system_category_product_remove
  get  '/system_categories/:id/game/:game_id/add' => 'system_categories#add_game', :as => :system_category_add_game
  get  '/system_categories/:id/character/:character_id/add' => 'system_categories#add_character', :as => :system_category_add_character
  put  '/system_categories/:id/update_views' => 'system_categories#update_views', :as => :system_category_update_views
  put  '/system_categories/:id/remove_profile_photo' => 'system_categories#remove_profile_photo', :as => :system_category_remove_profile_photo

  get  '/products/:id/system_categories' => 'products#system_categories', :as => :product_system_categories

  post '/ipn_subscription_notifications' => 'ipn_subscription_notifications#create', :as => :ipn_subscription_notifications
  post '/ipn_invoice_notifications' => 'ipn_invoice_notifications#create', :as => :ipn_invoice_notifications

  get  '/membership/premium_plans' => 'memberships#premium_membership', :as => :premium_membership
  get  '/membership/mythic' => 'memberships#mythic', :as => :mythic
  get  '/membership/thank_you' => 'memberships#thank_you', :as => :membership_thank_you
  get  '/membership/discounts' => 'memberships#discounts', :as => :membership_discounts
  get  '/users/:id/membership' => 'users#membership', :as => :user_membership

  get  '/flgs' => 'base#flgs'

  get  '/users/:user_id/games/:id' => 'games#show', :as => :user_game
  get  '/users/:user_id/characters/:id' => 'characters#show', :as => :user_character
  get  '/users/:user_id/events/:id' => 'events#show', :as => :user_event

  get  '/newsletter_user_list.:format' => 'users#newsletter_user_list'
  get  '/newsletter_admin_list.:format' => 'users#newsletter_admin_list'
  get  '/newsletter_power_user_list.:format' => 'users#newsletter_power_user_list'
  get  '/newsletter_publisher_list.:format' => 'users#newsletter_publisher_list'

  get  '/users/sideload' => 'users#sideload', :as => :sideload_user

  put  '/users/:id/change_profile_photo' => 'users#change_profile_photo', :as => :user_change_profile_photo
  put  '/users/:id/update_views' => 'users#update_views', :as => :user_update_views
  get  '/users/:id/grant_network_god_mode_access' => 'users#grant_network_god_mode_access', :as => :grant_network_god_mode_access
  get  '/users/:id/revoke_network_god_mode_access' => 'users#revoke_network_god_mode_access', :as => :revoke_network_god_mode_access
  get  '/users/:id/grant_event_admin' => 'users#grant_event_admin', :as => :grant_event_admin
  get  '/users/:id/revoke_event_admin' => 'users#revoke_event_admin', :as => :revoke_event_admin
  get  '/users/:id/grant_chat_admin' => 'users#grant_chat_admin', :as => :grant_chat_admin
  get  '/users/:id/revoke_chat_admin' => 'users#revoke_chat_admin', :as => :revoke_chat_admin
  get  '/users/:id/grant_user_admin' => 'users#grant_user_admin', :as => :grant_user_admin
  get  '/users/:id/revoke_user_admin' => 'users#revoke_user_admin', :as => :revoke_user_admin
  get  '/users/:id/grant_achievement_admin' => 'users#grant_achievement_admin', :as => :grant_achievement_admin
  get  '/users/:id/revoke_achievement_admin' => 'users#revoke_achievement_admin', :as => :revoke_achievement_admin
  get  '/users/:id/ban_user' => 'users#ban_user', :as => :ban_user
  get  '/users/:id/unban_user' => 'users#unban_user', :as => :unban_user
  get  '/users/:id/address' => 'addresses#show', :as => :user_address
  get  '/users/:id/address/update' => 'addresses#update', :as => :update_user_address
  get  '/users/:id/tshirt_details' => 'users#tshirt_details', :as => :user_tshirt_details
  get  '/users/:id/tshirt_details/update' => 'users#update_tshirt_details', :as => :update_user_tshirt_details

  get  '/users/:id/grant_epic' => 'users#grant_epic', :as => :grant_epic
  get  '/users/:id/grant_legendary' => 'users#grant_legendary', :as => :grant_legendary
  get  '/users/:id/grant_exalted' => 'users#grant_exalted', :as => :grant_exalted
  get  '/users/:id/grant_mythic' => 'users#grant_mythic', :as => :grant_mythic
  get  '/users/:id/revoke_premium' => 'users#revoke_premium', :as => :revoke_premium

  get  '/games/:id/unlocked_achievements' => 'achievements#unlocked_game', :as => :unlocked_game_achievements
  get  '/characters/:id/unlocked_achievements' => 'achievements#unlocked_character', :as => :unlocked_character_achievements
  get  '/users/:id/unlocked_achievements' => 'achievements#unlocked_user', :as => :unlocked_user_achievements
  get  '/users/:id/authored_achievements' => 'achievements#authored', :as => :authored_achievements
  get  '/users/:id/achievements/manage' => 'achievements#manage', :as => :manage_achievements
  get  '/users/:id/achievements/select' => 'achievements#select_user', :as => :select_user_achievements
  get  '/games/:id/achievements/select' => 'achievements#select_game', :as => :select_game_achievements
  get  '/characters/:id/achievements/select' => 'achievements#select_character', :as => :select_character_achievements

  get  '/achievement/leaderboard/top_by_level' => 'achievements#leaderboard_top_by_level', :as => :achievement_leaderboard_top_by_level
  get  '/achievement/leaderboard/top_by_count' => 'achievements#leaderboard_top_by_count', :as => :achievement_leaderboard_top_by_count
  get  '/achievement/leaderboard/top_authors' => 'achievements#leaderboard_top_authors', :as => :achievement_leaderboard_top_authors
  get  '/achievements/:id/grant/:recipient_type/:recipient_id' => 'achievements#grant', :as => :grant_achievement
  get  '/achievements/:id/revoke/:ua_id' => 'achievements#revoke', :as => :revoke_achievement
  get  '/achievements/:id/remove/:ua_id' => 'achievements#remove', :as => :remove_achievement
  get  '/achievements/:id/accept/:ua_id' => 'achievements#accept', :as => :accept_achievement
  get  '/achievements/:id/deny/:ua_id' => 'achievements#deny', :as => :deny_achievement

  get  '/users/:id/calendar/:year/:month' => 'users#calendar', :year => Time.zone.now.year, :month => Time.zone.now.month, :as => :user_calendar
  get  '/users/:id/characters' => 'users#characters', :as => :user_characters
  get  '/users/:id/games' => 'users#games', :as => :user_games
  get  '/users/:id/games_playing' => 'users#games_playing', :as => :user_games_playing

  put  '/characters/:id/update_views' => 'characters#update_views', :as => :character_update_views
  get  '/characters/:id/pick_profile_photo' => 'characters#pick_profile_photo', :as => :character_pick_profile_photo
  put  '/characters/:id/change_profile_photo' => 'characters#change_profile_photo', :as => :character_change_profile_photo
  get  '/characters/:id/new_avatar_photo' => 'characters#new_avatar_photo', :as => :new_character_avatar_photo
  get  '/characters/:id/game_table_sheet' => 'characters#game_table_sheet', :as => :game_table_sheet
  get  '/characters/:id/edit_clone' => 'characters#edit_clone', :as => :edit_character_clone
  get  '/characters/:id/sheet' => 'characters#sheet', :as => :sheet
  get  '/characters/:id/print' => 'characters#print'
  get  '/characters/:id/posts' => 'posts#character_index', :as => :character_post
  get  '/characters/:id/notepad' => 'characters#notepad', :as => :character_notepad
  get  '/characters/:id/edit_notepad' => 'characters#edit_notepad', :as => :character_edit_notepad
  patch  '/characters/:id/update_notepad' => 'characters#update_notepad', :as => :character_update_notepad
  get  '/characters/auto_complete_for_character_genre' => 'characters#auto_complete_for_character_genre', :as => :auto_complete_for_character_genre

  get  '/characters/:id/products/' => 'characters#products', :as => :character_products
  #get  '/characters/:id/product/search' => 'characters#product_search', :as => :character_product_search
  get  '/characters/:id/product/:product_id/add' => 'characters#product_add', :as => :character_product_add
  get  '/characters/:id/product/:product_id/remove' => 'characters#product_remove', :as => :character_product_remove

  put  '/games/:id/update_views' => 'games#update_views', :as => :game_update_views
  put  '/games/:id/change_profile_photo' => 'games#change_profile_photo', :as => :game_change_profile_photo
  get  '/games/:id/register_player_for_event/slot/:slot_id' => 'games#register_player_for_event', :as => :register_player_for_event
  get  '/games/:id/register_alternate_for_event/slot/:slot_id' => 'games#register_alternate_for_event', :as => :register_alternate_for_event

app/models/system_category.rb
class SystemCategory < ActiveRecord::Base
  #extend FriendlyId

  belongs_to :user
  validates_length_of("name", :minimum => 3)

  belongs_to  :avatar, :class_name => "Photo", :foreign_key => "avatar_id"

  #has_and_belongs_to_many :products
  has_many :system_category_products, :dependent => :destroy
  has_many :products, :through => :system_category_products

  #friendly_id :name, :use => [:slugged, :finders]

  #scope :popular, :order => 'system_categories.view_count DESC'

  acts_as_commentable
  acts_as_taggable

  def self.popular
     where('products_counter > 0').order('system_categories.view_count DESC')
  end

  def self.search_conditions(params)
    search = prepare_params_for_search(params)
    system_categories = build_conditions_for_search(search)
    return system_categories, search
  end


  def self.prepare_params_for_search(params)
    search = {}.merge(params)
    search['name'] = params[:name] || nil
    search['user_id'] = params[:user_id] || nil
    search
  end

  def self.build_conditions_for_search(search)
    system_categories = SystemCategory.popular

    if !search['user_id'].blank?
      system_categories = system_categories.where("user_id = ?", "%#{search['user_id'].strip}%")
    end
    if !search['name'].blank?
      system_categories = system_categories.where("name like ?", "%#{search['name'].strip}%")
    end

    system_categories
  end

  def owner
    self.user
  end
  
  def first_image_in_description(size = nil, options = {})
    doc = Hpricot( description )
    image = doc.at("img")
    image ? image['src'] : nil
  end
  
  def avatar_photo_url(size = nil)
    if avatar
      avatar.photo.url(size)
    else
      case size
        when :thumb
          configatron.photo['missing_thumb']
        else
          configatron.photo['missing_medium']
      end
    end
  end
end

app/views/system_categories/_form.html.haml
= error_messages_for :system_category

=form_for(@system_category, :html => {:class => "cmxform"}) do |system_category_form|
  .container
    .user_row 
      %fieldset
        %legend
          Category details
        %ol
          %li      
            = system_category_form.label 'Name'
            = system_category_form.text_field :name
      

    .user_row 
      %fieldset
        %legend
          Category description
        %ol
          %li      
            = system_category_form.text_area :description, :class => "rich_text_editor", :size => "100x20"

    %p
    = system_category_form.submit 'Save category'
  
  
          
          
  
  
  

app/views/system_categories/_profile_sidebar.html.haml
%p

.box
  %ul
    %li.view= link_to "All categories", system_categories_path
    - if current_user && (current_user == @system_category.owner || current_user.admin?)
      %li.view= link_to "Edit category", edit_system_category_path(@system_category)
      %li.view= link_to "Add product", system_category_product_search_path(@system_category)
      %li.view= link_to "Delete category", @system_category, data: {:confirm => 'Are you sure?'}, :method => :delete
      %li.view= link_to "Choose a category photo", :controller => "system_categories", :id => @system_category.id, :action => "pick_profile_photo"
      %li.view= link_to "Remove category photo", :controller => "system_categories", :id => @system_category.id, :action => "remove_profile_photo"
      - if current_user.admin?
        %li.view= link_to "Bump views", system_category_bump_views_path(@system_category)

    %li.view= "Views (#{@system_category.view_count})"
    -if DEPLOY_ADDTOANY
      %li.view
        =render :partial => "shared/addToAny"

    -if DEPLOY_ADDTHIS
      %li.view
        =render :partial => "shared/addThis"

app/views/system_categories/_publisher_profile.html.haml
.box
  %h3 Publisher
  .bio-block-post
    .bio-photo
      = link_to image_tag( user.avatar_photo_url(:thumb), "height"=>"50", "alt"=>"#{user.login}", "width"=>"50" ), user_path(user), :title => "#{user.login}'s"+ :profile.l
    %h3
      = link_to user.display_name, user_path(user), :class => 'url'
    %dd
    - if user.description
      = truncate_words( user.description, 12, '...')
    %dd.member
      =:member_since.l+" #{I18n.l(user.created_at, :format => :short_published_date)}"
    %dd.page
      - if user.posts.count == 1
        = link_to :singular_posts.l(:count => user.posts.count), user_posts_path(user)
      - else
        = link_to :plural_posts.l(:count => user.posts.count), user_posts_path(user)
    %dd.rss
      =link_to :rss_feed.l, user_posts_path(user, :format => :rss)

app/views/system_categories/_search_options.html.haml
-box :class => 'alt first_alt' do
  = link_to( "&raquo; #{:back_to_all_users.l}", users_path) if params['login'] || params['tag_list']
  = form_tag system_categories_path, :method => :get , :class => 'MainForm' do
    %label= "Name"
    = text_field_tag 'name', @search['name']
    %p
    -if @new_game
      = hidden_field_tag("new_game", @new_game)
    -if @game
      = hidden_field_tag("game_id", @game.id)
    -if @character
      = hidden_field_tag("character_id", @character.id)

    %input{"type"=>"submit", "value"=>"Search categories"}

app/views/system_categories/_sidebar_system_category.html.haml
.user_row
%h2
  = link_to system_category.name, system_category
  -if defined?action && action = 'add'
    -if defined?game
      .right= link_to 'Add', system_category_add_game_path(system_category, game)
    -elsif defined?character
      .right= link_to 'Add', system_category_add_character_path(system_category, character)
    -elsif defined?new_game
      .right= link_to 'Start', new_game_path(:system_category_id => system_category.id)

.center
  -system_category.products.first(3).each do |product|
    =render :partial => 'products/sidebar_product', :locals => {:product => product}

-#%a{:href=>"#{system_category_path(system_category)}", :class=>"photo", :rel=>"bookmark"}
-#  =render :partial => "system_categories/system_category_photo", :locals => {:system_category => system_category, :width =>"87"}

app/views/system_categories/_system_category.html.haml
.user_row

  .user_row_col1
    %a{:href=>"#{system_category_path(system_category)}"}
      .listing_photo=render :partial => "system_categories/system_category_photo", :locals => {:system_category => system_category, :width =>"162"}

  .user_row_col2
    %ul
      %li.view=  link_to system_category.name, system_category_path(system_category)
      -if defined?game_system
        %li.view=  link_to "Migrate", game_system_migrate_path(game_system, system_category)

  .user_row_col3b
    = truncate_words(system_category.description, 50, '...' )


    

app/views/system_categories/_system_category_avatar_sidebar.html.haml
.center
  %br
    .profile_photo=render :partial => "system_categories/system_category_photo", :locals => {:system_category => system_category}

app/views/system_categories/_system_category_photo.html.haml
- if !system_category.avatar.nil?
  =image_tag((system_category.avatar_photo_url(:medium)), :title=>system_category.name)
-elsif system_category.dtrpg_category_image
  .dtrpg_category_image=image_tag((configatron.DTRPG_IMAGE + system_category.dtrpg_category_image), :title=>system_category.name)
-elsif system_category.products.any?
  -if system_category.products.first.dtrpg_product_image
    =image_tag((system_category.products.first.dtrpg_product_image), :title=>system_category.name)
  - elsif !system_category.products.first.amazon_image_url.blank?
    =image_tag(system_category.products.first.amazon_image_url, :title=>system_category.name)
  -else
    =image_tag((system_category.products.first.avatar_photo_url(:medium)), :title=>system_category.name)
- else
  =image_tag(configatron.photo.missing_medium.to_s, :title=>system_category.name)

app/views/system_categories/_system_category_tile.html.haml
.box_tile

  %h2
    -if defined?new_game
      = link_to "Start a game using #{system_category.name}".html_safe, new_game_path(:system_category_id => system_category.id)
    -elsif defined?game
      = link_to "Add: #{system_category.name}".html_safe, system_category_add_game_path(system_category, game)
    -elsif defined?character
      = link_to "Add: #{system_category.name}".html_safe, system_category_add_character_path(system_category, character)
    -else
      = link_to system_category.name, system_category

    -#-if defined?action && action = 'add'
    -#  -if defined?game
    -#    .right= link_to 'Add', system_category_add_game_path(system_category, game)
    -#  -elsif defined?character
    -#    .right= link_to 'Add', system_category_add_character_path(system_category, character)

  %p
  .center
    -system_category.products.first(3).each do |product|
      =render :partial => 'products/sidebar_product', :locals => {:product => product}

  -#%a{:href=>"#{system_category_path(system_category)}", :class=>"photo", :rel=>"bookmark"}
  -#  =render :partial => "system_categories/system_category_photo", :locals => {:system_category => system_category, :width =>"87"}

app/views/system_categories/edit.html.haml
- @section = 'publishers'
.box
  %h3 Edit category
   
  = render :partial => "form"

app/views/system_categories/index.html.haml
-@meta = { :description => configatron.meta_description, :keywords => configatron.meta_keywords, :robots => configatron.robots_meta_show_content }


.tile_page_col_left
  = render :partial => 'system_categories/search_options'

  -if current_user
    .box
      -if @game
        %h2= link_to 'All categories', system_categories_path(:game_id => @game.id)
        %h2= link_to 'My categories', system_categories_path(:user_id => current_user.id, :game_id => @game.id)
      -elsif @character
        %h2= link_to 'All categories', system_categories_path(:character_id=>@character.id)
        %h2= link_to 'My categories', system_categories_path(:user_id => current_user.id, :character_id=>@character.id)
      -elsif @new_game
        %h2= link_to 'All categories', system_categories_path(:new_game=>@new_game)
        %h2= link_to 'My categories', system_categories_path(:user_id => current_user.id, :new_game=>@new_game)
      -else
        %h2= link_to 'All categories', system_categories_path
        %h2= link_to 'My categories', system_categories_path(:user_id => current_user.id)

      %h2= link_to 'Create category', new_system_category_path

      -if @game_system && current_user.admin?
        %ul
          %li.view= "#{@game_system.name} : Migrate".html_safe

      %br

      -if @game
        %h2= link_to 'All products', products_path(:game_id => @game.id)
        %h2= link_to 'My products', products_path(:publisher_id => current_user.id, :game_id => @game.id)
      -elsif @character
        %h2= link_to 'All products', products_path(:character_id => @character.id)
        %h2= link_to 'My products', products_path(:publisher_id => current_user.id, :character_id => @character.id)
      -elsif @new_game
        %h2= link_to 'All products', products_path(:new_game => @new_game)
        %h2= link_to 'My products', products_path(:publisher_id => current_user.id, :new_game => @new_game)
      -else
        %h2= link_to 'All products', products_path
        %h2= link_to 'My products', products_path(:publisher_id => current_user.id)

      -if current_user
        %h2= link_to 'Create product', new_product_path

      -if @new_game
        %br
        %h2= link_to 'Skip this step', new_game_path

      -if @game || @character
        %br
        -if @game
          %h2= link_to "Back to #{@game.name}'s profile", seo_game_path(@game)
        -elsif @character
          %h2= link_to "Back to #{@character.name}'s profile", seo_character_path(@character)

.tile_page_col_right
  -if @new_game
    .box_tile_header
      %h2 What kind of game are you running?
      %h3 Choosing a category is the best way to help players find your game.
  -elsif @game
    .box_tile_header
      %h2= "#{link_to @game.name, @game} : Add a category of products".html_safe
  -elsif @character
    .box_tile_header
      %h2= "#{link_to @character.name, @character} : Add a category of products".html_safe

  -if @result_count
    .box_tile_header
      %h2= "#{pluralize(number_with_delimiter(@result_count), 'category')} found"

  -@system_categories.each do |system_category|
    -if @game
      =render :partial => "system_categories/system_category_tile", :locals => {:system_category => system_category, :game => @game}
    -elsif @character
      =render :partial => "system_categories/system_category_tile", :locals => {:system_category => system_category, :character => @character}
    -elsif @new_game
      =render :partial => "system_categories/system_category_tile", :locals => {:system_category => system_category, :new_game => @new_game}
    -else
      =render :partial => "system_categories/system_category_tile", :locals => {:system_category => system_category}

  .clear_both
  %p
  %br

  .box_tile_header
    =paginate @system_categories

app/views/system_categories/new.html.haml
- @section = 'publishers'
.box
  %h3 Create category

  = render :partial => "form"

app/views/system_categories/pick_profile_photo.html.haml
#col1
  = render :partial => 'system_categories/system_category_avatar_sidebar', :locals => {:system_category => @system_category}
  = render :partial => 'system_categories/profile_sidebar'

#col2
  .box
    %h2= "#{link_to @system_category.name, system_category_path(@system_category)} : Select a profile photo".html_safe

  .box
    %h3= "Select a profile photo for #{@system_category.name}"
    %p= link_to( :new_photo.l, new_user_photo_path(@user))

    .clear
    - @photos.each do |photo|
      = link_to image_tag(photo.photo.url(:thumb)), system_category_change_profile_photo_path({:id => @system_category, :photo_id => photo}), :method => :put

  .box
    =paginate @photos

      

app/views/system_categories/show.html.haml
-#-description = "#{h(@system_category.name)}'s profile on #{configatron.community_name}. "
-#-description += "#{h(@system_category.description).gsub(/<\/?[^>]*>/, "").gsub(/  +/, "")} "
-#-description += configatron.meta_description
-#
-#- @meta = { :description => description, :keywords => "#{h(@system_category.name)}, #{configatron.meta_keywords}, #{h(@system_category.tags.join(", ")) unless @system_category.tags.nil?}", :robots => configatron.robots_meta_show_content }
- @section = 'publishers'

#col1
  =render :partial => "system_categories/system_category_avatar_sidebar", :locals => {:system_category=> @system_category}
  = render :partial => 'profile_sidebar', :locals => {:user => @system_category.owner}

    

#col2
  .box
    %h3
      = link_to @system_category.name, system_category_path(@system_category)

          
  - if !@system_category.description.blank?
    #about_me.box.alt
      =@system_category.description.html_safe

      
  -if @system_category.products.any?
    .box
      -@system_category.products.each do |product|
        -if current_user && (current_user == @system_category.owner || current_user.admin?)
          = render :partial => 'products/product', :locals => {:product=> product, :action => 'remove', :system_category => @system_category}
          -#= render :partial => 'products/product_listing_large', :locals => {:product=> product, :action => 'remove', :system_category => @system_category}
        -else
          = render :partial => 'products/product', :locals => {:product=> product}
          -#= render :partial => 'products/product_listing_large', :locals => {:product=> product}

  -##comments.box.alt
  -#  %p= render :partial => 'comments/comment_form', :locals => {:commentable => @system_category}
  -#
  -#  %a#newest_comment
  -#  = render :partial => 'comments/comment', :collection => @comments
  -#
  -#  / this shouldn't be needed, as any logged in user should be able to comment on a system_category
  -#  - @user = @system_category.owner
  -#  %span#more_comments_links= more_comments_links(@product)

%script{:type=>"text/javascript", :charset=>"utf-8"}
  = remote_function :url => {:controller => 'system_categories', :action => 'update_views', :id => @system_category}, :method => :put