config/routes.rb
Crit::Application.routes.draw do

  mount CommunityEngine::Engine => "/"

  #get  '/' => 'base#site_index', :as => :home

  resources :achievements
  resources :player_registrations
  resources :intake_survey
  resources :game_systems
  resources :properties
  resources :characters
  resources :games
  resources :events do
    resources :slots
  end
  resources :characters
  resources :products
  resources :system_categories

  post '/logout' => 'sessions#destroy', :as => :logout_button

  get  '/game_systems/:id/migrate/:system_category_id' => 'game_systems#migrate', :as => :game_system_migrate
  get  '/system_categories/search/:game_system_id' => 'system_categories#index', :as => :system_category_search
  get  '/system_categories/new_game' => 'system_categories#new_game', :as => :system_categories_new_game


  get  '/system_categories/:id/pick_profile_photo' => 'system_categories#pick_profile_photo', :as => :system_category_pick_profile_photo
  put  '/system_categories/:id/change_profile_photo' => 'system_categories#change_profile_photo', :as => :system_category_change_profile_photo
  get  '/system_categories/:id/bump_views' => 'system_categories#bump_views', :as => :system_category_bump_views
  get  '/system_categories/:id/product/search' => 'system_categories#product_search', :as => :system_category_product_search
  get  '/system_categories/:id/product/:product_id/add' => 'system_categories#product_add', :as => :system_category_product_add
  get  '/system_categories/:id/product/:product_id/remove' => 'system_categories#product_remove', :as => :system_category_product_remove
  get  '/system_categories/:id/game/:game_id/add' => 'system_categories#add_game', :as => :system_category_add_game
  get  '/system_categories/:id/character/:character_id/add' => 'system_categories#add_character', :as => :system_category_add_character
  put  '/system_categories/:id/update_views' => 'system_categories#update_views', :as => :system_category_update_views
  put  '/system_categories/:id/remove_profile_photo' => 'system_categories#remove_profile_photo', :as => :system_category_remove_profile_photo

  get  '/products/:id/system_categories' => 'products#system_categories', :as => :product_system_categories

  post '/ipn_subscription_notifications' => 'ipn_subscription_notifications#create', :as => :ipn_subscription_notifications
  post '/ipn_invoice_notifications' => 'ipn_invoice_notifications#create', :as => :ipn_invoice_notifications

  get  '/membership/premium_plans' => 'memberships#premium_membership', :as => :premium_membership
  get  '/membership/mythic' => 'memberships#mythic', :as => :mythic
  get  '/membership/thank_you' => 'memberships#thank_you', :as => :membership_thank_you
  get  '/membership/discounts' => 'memberships#discounts', :as => :membership_discounts
  get  '/users/:id/membership' => 'users#membership', :as => :user_membership

  get  '/flgs' => 'base#flgs'

  get  '/users/:user_id/games/:id' => 'games#show', :as => :user_game
  get  '/users/:user_id/characters/:id' => 'characters#show', :as => :user_character
  get  '/users/:user_id/events/:id' => 'events#show', :as => :user_event

  get  '/newsletter_user_list.:format' => 'users#newsletter_user_list'
  get  '/newsletter_admin_list.:format' => 'users#newsletter_admin_list'
  get  '/newsletter_power_user_list.:format' => 'users#newsletter_power_user_list'
  get  '/newsletter_publisher_list.:format' => 'users#newsletter_publisher_list'

  get  '/users/sideload' => 'users#sideload', :as => :sideload_user

  put  '/users/:id/change_profile_photo' => 'users#change_profile_photo', :as => :user_change_profile_photo
  put  '/users/:id/update_views' => 'users#update_views', :as => :user_update_views
  get  '/users/:id/grant_network_god_mode_access' => 'users#grant_network_god_mode_access', :as => :grant_network_god_mode_access
  get  '/users/:id/revoke_network_god_mode_access' => 'users#revoke_network_god_mode_access', :as => :revoke_network_god_mode_access
  get  '/users/:id/grant_event_admin' => 'users#grant_event_admin', :as => :grant_event_admin
  get  '/users/:id/revoke_event_admin' => 'users#revoke_event_admin', :as => :revoke_event_admin
  get  '/users/:id/grant_chat_admin' => 'users#grant_chat_admin', :as => :grant_chat_admin
  get  '/users/:id/revoke_chat_admin' => 'users#revoke_chat_admin', :as => :revoke_chat_admin
  get  '/users/:id/grant_user_admin' => 'users#grant_user_admin', :as => :grant_user_admin
  get  '/users/:id/revoke_user_admin' => 'users#revoke_user_admin', :as => :revoke_user_admin
  get  '/users/:id/grant_achievement_admin' => 'users#grant_achievement_admin', :as => :grant_achievement_admin
  get  '/users/:id/revoke_achievement_admin' => 'users#revoke_achievement_admin', :as => :revoke_achievement_admin
  get  '/users/:id/ban_user' => 'users#ban_user', :as => :ban_user
  get  '/users/:id/unban_user' => 'users#unban_user', :as => :unban_user
  get  '/users/:id/address' => 'addresses#show', :as => :user_address
  get  '/users/:id/address/update' => 'addresses#update', :as => :update_user_address
  get  '/users/:id/tshirt_details' => 'users#tshirt_details', :as => :user_tshirt_details
  get  '/users/:id/tshirt_details/update' => 'users#update_tshirt_details', :as => :update_user_tshirt_details

  get  '/users/:id/grant_epic' => 'users#grant_epic', :as => :grant_epic
  get  '/users/:id/grant_legendary' => 'users#grant_legendary', :as => :grant_legendary
  get  '/users/:id/grant_exalted' => 'users#grant_exalted', :as => :grant_exalted
  get  '/users/:id/grant_mythic' => 'users#grant_mythic', :as => :grant_mythic
  get  '/users/:id/revoke_premium' => 'users#revoke_premium', :as => :revoke_premium

  get  '/games/:id/unlocked_achievements' => 'achievements#unlocked_game', :as => :unlocked_game_achievements
  get  '/characters/:id/unlocked_achievements' => 'achievements#unlocked_character', :as => :unlocked_character_achievements
  get  '/users/:id/unlocked_achievements' => 'achievements#unlocked_user', :as => :unlocked_user_achievements
  get  '/users/:id/authored_achievements' => 'achievements#authored', :as => :authored_achievements
  get  '/users/:id/achievements/manage' => 'achievements#manage', :as => :manage_achievements
  get  '/users/:id/achievements/select' => 'achievements#select_user', :as => :select_user_achievements
  get  '/games/:id/achievements/select' => 'achievements#select_game', :as => :select_game_achievements
  get  '/characters/:id/achievements/select' => 'achievements#select_character', :as => :select_character_achievements

  get  '/achievement/leaderboard/top_by_level' => 'achievements#leaderboard_top_by_level', :as => :achievement_leaderboard_top_by_level
  get  '/achievement/leaderboard/top_by_count' => 'achievements#leaderboard_top_by_count', :as => :achievement_leaderboard_top_by_count
  get  '/achievement/leaderboard/top_authors' => 'achievements#leaderboard_top_authors', :as => :achievement_leaderboard_top_authors
  get  '/achievements/:id/grant/:recipient_type/:recipient_id' => 'achievements#grant', :as => :grant_achievement
  get  '/achievements/:id/revoke/:ua_id' => 'achievements#revoke', :as => :revoke_achievement
  get  '/achievements/:id/remove/:ua_id' => 'achievements#remove', :as => :remove_achievement
  get  '/achievements/:id/accept/:ua_id' => 'achievements#accept', :as => :accept_achievement
  get  '/achievements/:id/deny/:ua_id' => 'achievements#deny', :as => :deny_achievement

  get  '/users/:id/calendar/:year/:month' => 'users#calendar', :year => Time.zone.now.year, :month => Time.zone.now.month, :as => :user_calendar
  get  '/users/:id/characters' => 'users#characters', :as => :user_characters
  get  '/users/:id/games' => 'users#games', :as => :user_games
  get  '/users/:id/games_playing' => 'users#games_playing', :as => :user_games_playing

  put  '/characters/:id/update_views' => 'characters#update_views', :as => :character_update_views
  get  '/characters/:id/pick_profile_photo' => 'characters#pick_profile_photo', :as => :character_pick_profile_photo
  put  '/characters/:id/change_profile_photo' => 'characters#change_profile_photo', :as => :character_change_profile_photo
  get  '/characters/:id/new_avatar_photo' => 'characters#new_avatar_photo', :as => :new_character_avatar_photo
  get  '/characters/:id/game_table_sheet' => 'characters#game_table_sheet', :as => :game_table_sheet
  get  '/characters/:id/edit_clone' => 'characters#edit_clone', :as => :edit_character_clone
  get  '/characters/:id/sheet' => 'characters#sheet', :as => :sheet
  get  '/characters/:id/print' => 'characters#print'
  get  '/characters/:id/posts' => 'posts#character_index', :as => :character_post
  get  '/characters/:id/notepad' => 'characters#notepad', :as => :character_notepad
  get  '/characters/:id/edit_notepad' => 'characters#edit_notepad', :as => :character_edit_notepad
  patch  '/characters/:id/update_notepad' => 'characters#update_notepad', :as => :character_update_notepad
  get  '/characters/auto_complete_for_character_genre' => 'characters#auto_complete_for_character_genre', :as => :auto_complete_for_character_genre

  get  '/characters/:id/products/' => 'characters#products', :as => :character_products
  #get  '/characters/:id/product/search' => 'characters#product_search', :as => :character_product_search
  get  '/characters/:id/product/:product_id/add' => 'characters#product_add', :as => :character_product_add
  get  '/characters/:id/product/:product_id/remove' => 'characters#product_remove', :as => :character_product_remove

  put  '/games/:id/update_views' => 'games#update_views', :as => :game_update_views
  put  '/games/:id/change_profile_photo' => 'games#change_profile_photo', :as => :game_change_profile_photo
  get  '/games/:id/register_player_for_event/slot/:slot_id' => 'games#register_player_for_event', :as => :register_player_for_event
  get  '/games/:id/register_alternate_for_event/slot/:slot_id' => 'games#register_alternate_for_event', :as => :register_alternate_for_event

app/views/user_notifier/_goodbye_and_footer.html.erb
See you soon!
The <%= configatron.community_name %> team

-------------------------------
If you don't want to receive email notifications like this one from <%= configatron.community_name %>, you can change your preferences here:
<%= user_url @user %>/edit_account

app/views/user_notifier/access_violation_notice.html.erb
User name: <%= @user_display_name  %>
Profile: <%= @user_path  %>
Attempted action: <%= @attempted_action %>

Request
* URL       : <%= raw @request.url %>
* IP address: <%= raw @request.remote_ip %>
* Parameters: <%= raw @request.filtered_parameters.inspect %>
* Rails root: <%= raw Rails.root %>

Session
* session id: <%= raw @request.session['session_id'].inspect.html_safe %>
* data: <%= raw PP.pp(@request.session, "") %>

<!--Environment-->
<!--<% filtered_env = @request.filtered_env -%>-->
<!--<% max = filtered_env.keys.max { |a, b| a.length <=> b.length } -%>-->
<!--<% filtered_env.keys.sort.each do |key| -%>-->
<!--  <%= raw("%-*s: %s" % [max.length, key, inspect_object(filtered_env[key])]) %> -->
<!--<% end -%>-->

* Process: <%= raw $$ %>
* Server : <%= raw `hostname -s`.chomp %>

app/views/user_notifier/beta_invite.html.erb
Hello <%= @invitee_name %>!

<%= @inviter_name %> asked me send you an invite for Infrno. It's a socnet/virtual game table for playing table-top
RPGs over the internet. 

We're in private beta, and still in stealth, so please keep this under wraps.

Here's your invite:
http://infrno.net
beta invite code: <%= @beta_invite_code %>

The real meat of the site is the game table, which you can find by clicking 'Game table - PLAY GAME!' in the left nav on any game
profile of which you are a member or owner. However, the sample game is open to all:
http://infrno.net/games/play/19

We have also invented a brand new way to enjoy and show off your games: post-session, in-character blogging. Check out the blog on
Sorena's profile page:
http://infrno.net/characters/25

Any and all feedback is highly appreciated.

Come get some!
Mike

app/views/user_notifier/chat_admin_granted_notice.html.erb
<%= render :partial => 'user_notifier/greeting', :locals => {:user => @user}  %>
Congratulations! You have been granted chat admin status.

The only new ability this enables is 'ban', which is IP and session based. That cheese-log can come back later, let's hope with some more manners.

Please use this sparingly, with forewarning, and report to support@infrno.net afterwards with the user's info and appropriate details.

Thank you for helping us keep Infrno a friendly place!

<%= render :partial => 'user_notifier/goodbye_and_footer', :locals => {:user => @user}  %>

app/views/user_notifier/chat_admin_revoked_notice.html.erb
<%= render :partial => 'user_notifier/greeting', :locals => {:user => @user}  %>

Your chat admin status has been revoked.

Please direct questions to support@infrno.net.

<%= render :partial => 'user_notifier/goodbye_and_footer', :locals => {:user => @user}  %>

app/views/user_notifier/friendship_request.html.erb
<%= render :partial => 'user_notifier/greeting', :locals => {:user => @user}  %>

<%= @requester.display_name %> would like to be friends with you:
<%= @url %> 

<%= render :partial => 'user_notifier/goodbye_and_footer', :locals => {:user => @user}  %>

app/views/user_notifier/game_approve_pregenerated_notice.html.erb
<%= render :partial => 'user_notifier/greeting', :locals => {:user => @user}  %>

Your regsitration for <%= h @pregeneratedCharacterRequest.character.name %> has been approved for <%= h @game.name %>

You can see the game's current roster of players and characters here:
<%= registration_desk_url(@game) %>

The next game time is scheduled for <%= @game.start_at.strftime('%a, %b %d, %Y') %>, at <%= @game.start_at.strftime('%I:%M%p %Z') %>
                
<%= render :partial => 'user_notifier/goodbye_and_footer', :locals => {:user => @user}  %>

app/views/user_notifier/game_character_leave_notice.html.erb
<%= render :partial => 'user_notifier/greeting', :locals => {:user => @user}  %>

<%= h @registration.character.name %> has left your game, <%= h @game.name %>

You can see the game's current roster of players and characters here:
<%= registration_desk_url(@game) %>
                
<%= render :partial => 'user_notifier/goodbye_and_footer', :locals => {:user => @user}  %>

app/views/user_notifier/game_join_pregenerated_notice.html.erb
<%= render :partial => 'user_notifier/greeting', :locals => {:user => @user}  %>

<%= h @pregeneratedCharacterRequest.owner.display_name %> has asked to join <%= @game.name %> using a pregenerated character, <%= h @pregeneratedCharacterRequest.character.name %>

<%= character_url(@pregeneratedCharacterRequest.character) %>


You can approve or deny their application right here:  
Approve: <%= approve_pregenerated_url(@game, :character_id => @pregeneratedCharacterRequest.character.id, :user_id => @pregeneratedCharacterRequest.owner.id) %>
Deny: <%= deny_pregenerated_url(@game, :character_id => @pregeneratedCharacterRequest.character.id, :user_id => @pregeneratedCharacterRequest.owner.id) %>
  
You can see the game's current roster of players and characters here:
<%= registration_desk_url(@game) %>
                
<%= render :partial => 'user_notifier/goodbye_and_footer', :locals => {:user => @user}  %>

app/views/user_notifier/new_game_notice.html.erb
Hello!

A new <%= h @game.system_name %> game has been created on Infrno: <%= h @game.name %>

<%= h @game.description.gsub(/<\/?[^>]*>/, "") if !@game.description.blank? %>

<%= h @game.premise.gsub(/<\/?[^>]*>/, "") if !@game.premise.blank? %>

<%= h @game.style_of_play.gsub(/<\/?[^>]*>/, "") if !@game.style_of_play.blank? %>

You can see the game's profile here:
  <%= game_url(@game) %>
                
Hope to see you hanging out on <%= configatron.community_name %> really soon!
The <%= configatron.community_name %> team

---------------------------------------------------------------------------------
If you don't want to receive e-mails like this one from <%= configatron.community_name %>, you can change 
your e-mail preferences here:

<%= home_url %>

app/views/user_notifier/publisher_beta_invite.html.erb
Hello <%= @invitee_name %>!

<%= @inviter_name %> asked me send you an invite for Infrno, to create your vendor account.

Infrno is a socnet/virtual game table for playing table-top RPGs over the internet. It's a great way to connect with your fans, and sell more product by getting it in front of the community.

We're in private beta, and still in stealth, so please keep this under wraps.

Here's your invitation to create a vendor account:
http://infrno.net/vendor_invite
beta invite code: <%= @beta_invite_code %>

Any and all feedback is highly appreciated.

Come get some!
Mike

app/views/user_notifier/slot_register_game_notice.html.erb
<%= render :partial => 'user_notifier/greeting', :locals => {:user => @slotGameRegistration.slot.event.owner}  %>

<%= @slotGameRegistration.game.owner.display_name %> has registered '<%= @slotGameRegistration.game.name %>' for '<%= @slotGameRegistration.slot.event.name %>'.

You can manage active and pending games here:
<%= event_url(@slotGameRegistration.slot.event) %>
                
<%= render :partial => 'user_notifier/goodbye_and_footer', :locals => {:user => @slotGameRegistration.slot.event.owner}  %>

app/views/user_notifier/user_admin_granted_notice.html.erb
<%= render :partial => 'user_notifier/greeting', :locals => {:user => @user}  %>
Congratulations! You have been granted user admin status.

Spam sucks, and while we've rolled out things like the registration captcha, some spam still gets through. If you see spam, you now have the ability to nuke the bastard from orbit.

User profile and blog post pages now have a 'User Admin' section, in the left column. This data is provided to help you determine if the user is a spammer:

    * created at: Dec 16, 2011
    * activated at: Dec 16, 2011
    * last request at: 17 hours ago
    * email: staging6547@infrno.net
    * 3 logins
    * 1 blog posts
    * 4 games
    * 0 characters
    * 1 friends
    * 0 comments
    * 5 activities
    * 0 forum posts

New accounts with no friends, games, or other such things, are very likely to be spam. It's a judgement call. The 'delete user' link in this section will do just that, along with any content associated with the user.

This is a non-recoverable action. Please be careful!

Thank you for helping us keep Infrno spam free!

<%= render :partial => 'user_notifier/goodbye_and_footer', :locals => {:user => @user}  %>

app/views/user_notifier/user_admin_revoked_notice.html.erb
<%= render :partial => 'user_notifier/greeting', :locals => {:user => @user}  %>

Your user admin status has been revoked.

Please direct questions to support@infrno.net.

<%= render :partial => 'user_notifier/goodbye_and_footer', :locals => {:user => @user}  %>