config/routes.rb
Crit::Application.routes.draw do

  mount CommunityEngine::Engine => "/"

  #get  '/' => 'base#site_index', :as => :home

  resources :achievements
  resources :player_registrations
  resources :intake_survey
  resources :game_systems
  resources :properties
  resources :characters
  resources :games
  resources :events do
    resources :slots
  end
  resources :characters
  resources :products
  resources :system_categories

  post '/logout' => 'sessions#destroy', :as => :logout_button

  get  '/game_systems/:id/migrate/:system_category_id' => 'game_systems#migrate', :as => :game_system_migrate
  get  '/system_categories/search/:game_system_id' => 'system_categories#index', :as => :system_category_search
  get  '/system_categories/new_game' => 'system_categories#new_game', :as => :system_categories_new_game


  get  '/system_categories/:id/pick_profile_photo' => 'system_categories#pick_profile_photo', :as => :system_category_pick_profile_photo
  put  '/system_categories/:id/change_profile_photo' => 'system_categories#change_profile_photo', :as => :system_category_change_profile_photo
  get  '/system_categories/:id/bump_views' => 'system_categories#bump_views', :as => :system_category_bump_views
  get  '/system_categories/:id/product/search' => 'system_categories#product_search', :as => :system_category_product_search
  get  '/system_categories/:id/product/:product_id/add' => 'system_categories#product_add', :as => :system_category_product_add
  get  '/system_categories/:id/product/:product_id/remove' => 'system_categories#product_remove', :as => :system_category_product_remove
  get  '/system_categories/:id/game/:game_id/add' => 'system_categories#add_game', :as => :system_category_add_game
  get  '/system_categories/:id/character/:character_id/add' => 'system_categories#add_character', :as => :system_category_add_character
  put  '/system_categories/:id/update_views' => 'system_categories#update_views', :as => :system_category_update_views
  put  '/system_categories/:id/remove_profile_photo' => 'system_categories#remove_profile_photo', :as => :system_category_remove_profile_photo

  get  '/products/:id/system_categories' => 'products#system_categories', :as => :product_system_categories

  post '/ipn_subscription_notifications' => 'ipn_subscription_notifications#create', :as => :ipn_subscription_notifications
  post '/ipn_invoice_notifications' => 'ipn_invoice_notifications#create', :as => :ipn_invoice_notifications

  get  '/membership/premium_plans' => 'memberships#premium_membership', :as => :premium_membership
  get  '/membership/mythic' => 'memberships#mythic', :as => :mythic
  get  '/membership/thank_you' => 'memberships#thank_you', :as => :membership_thank_you
  get  '/membership/discounts' => 'memberships#discounts', :as => :membership_discounts
  get  '/users/:id/membership' => 'users#membership', :as => :user_membership

  get  '/flgs' => 'base#flgs'

  get  '/users/:user_id/games/:id' => 'games#show', :as => :user_game
  get  '/users/:user_id/characters/:id' => 'characters#show', :as => :user_character
  get  '/users/:user_id/events/:id' => 'events#show', :as => :user_event

  get  '/newsletter_user_list.:format' => 'users#newsletter_user_list'
  get  '/newsletter_admin_list.:format' => 'users#newsletter_admin_list'
  get  '/newsletter_power_user_list.:format' => 'users#newsletter_power_user_list'
  get  '/newsletter_publisher_list.:format' => 'users#newsletter_publisher_list'

  get  '/users/sideload' => 'users#sideload', :as => :sideload_user

  put  '/users/:id/change_profile_photo' => 'users#change_profile_photo', :as => :user_change_profile_photo
  put  '/users/:id/update_views' => 'users#update_views', :as => :user_update_views
  get  '/users/:id/grant_network_god_mode_access' => 'users#grant_network_god_mode_access', :as => :grant_network_god_mode_access
  get  '/users/:id/revoke_network_god_mode_access' => 'users#revoke_network_god_mode_access', :as => :revoke_network_god_mode_access
  get  '/users/:id/grant_event_admin' => 'users#grant_event_admin', :as => :grant_event_admin
  get  '/users/:id/revoke_event_admin' => 'users#revoke_event_admin', :as => :revoke_event_admin
  get  '/users/:id/grant_chat_admin' => 'users#grant_chat_admin', :as => :grant_chat_admin
  get  '/users/:id/revoke_chat_admin' => 'users#revoke_chat_admin', :as => :revoke_chat_admin
  get  '/users/:id/grant_user_admin' => 'users#grant_user_admin', :as => :grant_user_admin
  get  '/users/:id/revoke_user_admin' => 'users#revoke_user_admin', :as => :revoke_user_admin
  get  '/users/:id/grant_achievement_admin' => 'users#grant_achievement_admin', :as => :grant_achievement_admin
  get  '/users/:id/revoke_achievement_admin' => 'users#revoke_achievement_admin', :as => :revoke_achievement_admin
  get  '/users/:id/ban_user' => 'users#ban_user', :as => :ban_user
  get  '/users/:id/unban_user' => 'users#unban_user', :as => :unban_user
  get  '/users/:id/address' => 'addresses#show', :as => :user_address
  get  '/users/:id/address/update' => 'addresses#update', :as => :update_user_address
  get  '/users/:id/tshirt_details' => 'users#tshirt_details', :as => :user_tshirt_details
  get  '/users/:id/tshirt_details/update' => 'users#update_tshirt_details', :as => :update_user_tshirt_details

  get  '/users/:id/grant_epic' => 'users#grant_epic', :as => :grant_epic
  get  '/users/:id/grant_legendary' => 'users#grant_legendary', :as => :grant_legendary
  get  '/users/:id/grant_exalted' => 'users#grant_exalted', :as => :grant_exalted
  get  '/users/:id/grant_mythic' => 'users#grant_mythic', :as => :grant_mythic
  get  '/users/:id/revoke_premium' => 'users#revoke_premium', :as => :revoke_premium

  get  '/games/:id/unlocked_achievements' => 'achievements#unlocked_game', :as => :unlocked_game_achievements
  get  '/characters/:id/unlocked_achievements' => 'achievements#unlocked_character', :as => :unlocked_character_achievements
  get  '/users/:id/unlocked_achievements' => 'achievements#unlocked_user', :as => :unlocked_user_achievements
  get  '/users/:id/authored_achievements' => 'achievements#authored', :as => :authored_achievements
  get  '/users/:id/achievements/manage' => 'achievements#manage', :as => :manage_achievements
  get  '/users/:id/achievements/select' => 'achievements#select_user', :as => :select_user_achievements
  get  '/games/:id/achievements/select' => 'achievements#select_game', :as => :select_game_achievements
  get  '/characters/:id/achievements/select' => 'achievements#select_character', :as => :select_character_achievements

  get  '/achievement/leaderboard/top_by_level' => 'achievements#leaderboard_top_by_level', :as => :achievement_leaderboard_top_by_level
  get  '/achievement/leaderboard/top_by_count' => 'achievements#leaderboard_top_by_count', :as => :achievement_leaderboard_top_by_count
  get  '/achievement/leaderboard/top_authors' => 'achievements#leaderboard_top_authors', :as => :achievement_leaderboard_top_authors
  get  '/achievements/:id/grant/:recipient_type/:recipient_id' => 'achievements#grant', :as => :grant_achievement
  get  '/achievements/:id/revoke/:ua_id' => 'achievements#revoke', :as => :revoke_achievement
  get  '/achievements/:id/remove/:ua_id' => 'achievements#remove', :as => :remove_achievement
  get  '/achievements/:id/accept/:ua_id' => 'achievements#accept', :as => :accept_achievement
  get  '/achievements/:id/deny/:ua_id' => 'achievements#deny', :as => :deny_achievement

  get  '/users/:id/calendar/:year/:month' => 'users#calendar', :year => Time.zone.now.year, :month => Time.zone.now.month, :as => :user_calendar
  get  '/users/:id/characters' => 'users#characters', :as => :user_characters
  get  '/users/:id/games' => 'users#games', :as => :user_games
  get  '/users/:id/games_playing' => 'users#games_playing', :as => :user_games_playing

  put  '/characters/:id/update_views' => 'characters#update_views', :as => :character_update_views
  get  '/characters/:id/pick_profile_photo' => 'characters#pick_profile_photo', :as => :character_pick_profile_photo
  put  '/characters/:id/change_profile_photo' => 'characters#change_profile_photo', :as => :character_change_profile_photo
  get  '/characters/:id/new_avatar_photo' => 'characters#new_avatar_photo', :as => :new_character_avatar_photo
  get  '/characters/:id/game_table_sheet' => 'characters#game_table_sheet', :as => :game_table_sheet
  get  '/characters/:id/edit_clone' => 'characters#edit_clone', :as => :edit_character_clone
  get  '/characters/:id/sheet' => 'characters#sheet', :as => :sheet
  get  '/characters/:id/print' => 'characters#print'
  get  '/characters/:id/posts' => 'posts#character_index', :as => :character_post
  get  '/characters/:id/notepad' => 'characters#notepad', :as => :character_notepad
  get  '/characters/:id/edit_notepad' => 'characters#edit_notepad', :as => :character_edit_notepad
  patch  '/characters/:id/update_notepad' => 'characters#update_notepad', :as => :character_update_notepad
  get  '/characters/auto_complete_for_character_genre' => 'characters#auto_complete_for_character_genre', :as => :auto_complete_for_character_genre

  get  '/characters/:id/products/' => 'characters#products', :as => :character_products
  #get  '/characters/:id/product/search' => 'characters#product_search', :as => :character_product_search
  get  '/characters/:id/product/:product_id/add' => 'characters#product_add', :as => :character_product_add
  get  '/characters/:id/product/:product_id/remove' => 'characters#product_remove', :as => :character_product_remove

  put  '/games/:id/update_views' => 'games#update_views', :as => :game_update_views
  put  '/games/:id/change_profile_photo' => 'games#change_profile_photo', :as => :game_change_profile_photo
  get  '/games/:id/register_player_for_event/slot/:slot_id' => 'games#register_player_for_event', :as => :register_player_for_event
  get  '/games/:id/register_alternate_for_event/slot/:slot_id' => 'games#register_alternate_for_event', :as => :register_alternate_for_event

app/views/shared/_ad.html.haml
-#
-#-if current_user.nil? || current_user.membership_level == 0
-#  .box.center
-#    -#%h3=link_to "Upgrade, and banish ads!", premium_membership_path
-#    =render :partial => "ads/#{random_google_adwords_ad}"
-#
-#    %h3=link_to "Banish ads", premium_membership_path

app/views/shared/_admin_nav.html.haml
-box do
  %h3=:admin.l

  %ul.list
    %li= link_to_unless_current 'Game systems', admin_game_systems_path
    %li= link_to_unless_current :features.l, homepage_features_path
    /- if feature_enabled?('categories')
    /  %li= link_to_unless_current :categories.l, categories_path
    /- if feature_enabled?('contests')
    /  %li= link_to_unless_current :contests.l, contests_path
    %li= link_to_unless_current :metro_areas.l, metro_areas_path
    /- if feature_enabled?('skills')
    /  %li= link_to_unless_current :skills.l, new_skill_path
    /- if feature_enabled?('events')
    /  %li= link_to_unless_current :events.l, admin_events_path
    %li= link_to_unless_current :statistics.l, statistics_path
    %li= link_to_unless_current :ads.l, ads_path 
    %li= link_to_unless_current :comments.l, admin_comments_path 
    %li= link_to_unless_current :tags.l, admin_tags_path
    %li= link_to_unless_current :admin_pages.l, admin_pages_path

app/views/shared/_amazon_ad_wrapper.html.haml
-#-if current_user.nil? || current_user.membership_level == 0
-#  .box.center
-#    =render :partial => "shared/amazon_ad"
-#    %h3=link_to "Banish ads!", premium_membership_path

app/views/shared/_bio_help.html.haml
- if @user.vendor?
  = :user_vendor_offer.l
- elsif @user.publisher?

  Your company’s description is the first thing people see on your profile. Some ideas:
  %p
  Describe your company philosophy/culture
  %br
  Describe the products you are most proud of and why
  %br
  What kinds of exciting things are in the works right now
  %p

- else
  = :user_bio_help.l

app/views/shared/_end_javascript.html.haml
-#= javascript_include_tag 'community_engine'
= tiny_mce_init_if_needed

-#-if  (controller_name == 'events' && action_name == 'edit')
  -#=javascript_include_tag "jquery.datetimepicker"
  -#=stylesheet_link_tag "jquery.datetimepicker"

-#=javascript_include_tag "jquery.datetimepicker"
-#=stylesheet_link_tag "jquery.datetimepicker"

app/views/shared/_explore.html.haml
- if !logged_in?
  .box
    %h3 Want to be infrnal?
    %h3= link_to "Sign up for the free beta!", signup_url
    
.box
  %h3 
    Welcome to 
    =link_to "Infrno!", home_url
  %ul.list.checks
    - Category.find(:all).each do |c|
      %li= link_to c.name, category_path(c)
    
    %li= link_to "What's hot", popular_url, {:class => 'popular'}
    %li= link_to "What's recent", recent_url, {:class => 'recent'}
    
    -if current_user
      %li= link_to "Dashboard", dashboard_user_path(current_user)
    
    - Page.find(:all).each do |page|
      - if (logged_in? || page.page_public)
        %li= link_to page.title, pages_path(page)
        
    %li= link_to "Contact us", contact_url      
    
    - if @rss_title && @rss_url
      %li#rss= link_to :rss.l, @rss_url, {:title => @rss_title}
        

app/views/shared/_footer_content.html.haml
-if @popular_posts.any?
  .sub-box
    %h3 What's hot
    = render :partial => 'posts/post', :collection => @popular_posts

.sub-box
  %h3
    What's recent,
    = link_to 'see all', activities_path
  - @recent_activity.each do |activity|
    =render :partial => "activities/activity", :locals => {:activity => activity }

app/views/shared/_header.html.haml
#contentHeader

  %a{:href=>home_url, :class => "logo", :title=>"#{configatron.community_name}"}
  
  -if !defined? @hide_nav_items
    -if current_user
      =form_tag logout_button_path, :class => 'MainForm', :name => "logout_form" do
        %ul.logoutbar
          %li
            = submit_tag 'Logout', :class => 'button'

    -else
      =form_tag sessions_path, :class => 'MainForm', :name => "login_form" do
        %ul.loginbar
          %li
            = text_field_tag 'login', "Username", :class => "textbox", :style => "width: 100px", :onFocus => "if(this.value == 'Username') {this.value = '';}", :onBlur => "if (this.value == '') {this.value = 'Username';}"
          %li
            = password_field_tag 'password', "Password", :class => "textbox", :style => "width: 100px",  :onFocus => "if(this.value == 'Password') {this.value = '';}", :onBlur => "if (this.value == '') {this.value = 'Password';}"
          %li
            = submit_tag 'Login', :class => 'button'

    .auto_width
      -if FACEBOOK_CONNECT
        = link_to(image_tag("facebook_small_f.gif", :alt => 'Sign in with facebook'), "/auth/facebook", :title => 'Sign in with facebook')
      
        
 
  %ul{:class => "navbar"}
    -if !defined? @hide_nav_items
      -if current_user
        %li{:class =>"profile"}
          %a{:href=> user_path(current_user) }
      -else
        %li{:class =>"signup"}
          %a{:href=> signup_url}

      %li{:class =>"people"}
        %a{:href=> users_path }
      %li{:class =>"characters"}
        %a{:href=> characters_path }
      %li{:class =>"games"}
        %a{:href=> games_path }
      %li{:class =>"vendors"}
        %a{:href=> publishers_path }
      %li{:class =>"forums_nav"}
        %a{:href=> forums_path }
      %li{:class =>"feedback"}
        %a{:href=> contact_url }
      
  :plain
    <a class="gencon" href="http://gencon.com" title="Gen Con"> </a>

  -#-if !defined? @hide_nav_items
  -#  -if current_user.nil? || current_user.membership_level == 0
  -#    .banner_468x60
  -#      = link_to(image_tag("dtrpg_affiliatebanner2.gif", :alt => 'DriveThurRPG.com'), "http://rpg.drivethrustuff.com/index.php?affiliate_id=310477", :title => "DriveThruRPG.com")

     

app/views/shared/_home_page_user_profile.html.haml
.box
  -if logged_in?
    %h3= "Hello #{link_to(h(current_user.display_name), user_path(current_user))}".html_safe
  -else
    %h3= "Welcome to Infrno!"

  .box_row
    .user_row_col1
      -if logged_in?
        %p= link_to image_tag(current_user.avatar_photo_url(:thumb), :width => '120px' ), user_path(current_user)
      -else
        %p= image_tag('bug_290.png', :width => '120px' )
    .user_row_col2
      %ul
        -if logged_in?
          %li.compose
            = link_to "Inbox (#{current_user.unread_message_count} unread)", user_messages_path(current_user)

          -if current_user.total_pending_achievments_count > 0
            %li.view
              = link_to("Pending achievements", unlocked_user_achievements_path(current_user))


          -if current_user.pending_friendships.size > 0
            %li.view
              = link_to "Friend requests (#{current_user.pending_friendships.size})", pending_user_friendships_path(current_user)

        -if !logged_in? || (logged_in? && Time.now < current_user.activated_at + 1.month)
          %li.view= link_to("What is Infrno?", :controller => 'base', :action => 'welcome')
          %li.view= link_to("Show me the tour", user_post_path(@site_tour_post.user, @site_tour_post))
          %li.view= link_to("Show me the game table", user_post_path(@game_table_tour_post.user, @game_table_tour_post))

          /-if !GAMETABLE_DOWN_FOR_MAINT
          /  %li.view= link_to "Test drive the game table", :controller => "games", :action => "play", :id => @sample_game.id

          /  %li.view= link_to Page.find(1).title, pages_path(Page.find(1))
          /  %li.view= link_to Page.find(2).title, pages_path(Page.find(2))


        %li.view= link_to("Global activity feed", activities_path)
        -if current_user
          -#this generates a routing error, wtf by the bucket
          -#%li.view= link_to("Personal activity feed", network_user_activities_path)
          %li.view= link_to("Notifications", "/users/#{current_user.login_slug}/activities/network")
        %li.view= link_to("Achievement leaderboards", achievement_leaderboard_top_by_level_path)

        -#%li.view= link_to("Dev blog", "/tags/tech tips/Post")
        -#%li.view= link_to("Shwag", "http://infrno.spreadshirt.com/")



.box
  %h3 Your upcoming games
  -if @games_starting_soon &&  @games_starting_soon.size > 0
    -@games_starting_soon.each do |g|
      =render :partial => 'games/sidebar_game_starting_soon', :locals => { :game => g}
  -else
    You have none, find some!!
    %li.view= link_to("Game listings", games_path)
    %li.view= link_to("Players seeking games", "/forums/12")
    %li.view= link_to("Games seeking players", "/forums/13")

-if logged_in? && Time.now < current_user.activated_at + 1.month
  .box
    .box_row
      .user_row_col1
        = link_to image_tag(@sample_game.avatar_photo_url(:thumb), :alt => "#{@sample_game.name}", :width => '50', :height => '50'), game_path(@sample_game)
      .user_row_col2
        %h3=link_to h(@sample_game.name), game_path(@sample_game), :class => 'url'
        %ul
          %li.view
            -if GAMETABLE_DOWN_FOR_MAINT
              Game table is down for upgrades, brb!
            -else
              = link_to "Game table", gametable_url(@sample_game.id)




-#- kieara = User.find(5)
-#.box
-#  %h3= "Kiera's blog, #{link_to 'see all', user_posts_path(kieara)}".html_safe
-#  -kieara.posts.find_recent(:limit => 3).each do |post|
-#    =render :partial => 'posts/post_listing_on_sidebar', :locals => { :post => post }



-#-if @featured_writers.any?
-#  .box
-#    %h3
-#      =:featured_writer.l
-#    -@featured_writers.each do |user|
-#      =render :partial => "users/sidebar_user", :locals => {:user => user}

.box
  %h3 Active users
  -@active_users.each do |user|
    =render :partial => "users/sidebar_user", :locals => {:user => user}



=render :partial => "shared/amazon_ad_wrapper"
=render :partial => "tags/tags"
=render :partial => "shared/ad"

app/views/shared/_login_help.html.haml
.box
  %h3=:forgot_your_password.l
  =form_tag forgot_password_url, :class => 'MainForm' do
    %label{"for"=>"email"}=:enter_your_email_address.l+":"
    = text_field_tag 'email', nil, :size => 35
    %p
      = submit_tag "Send me a new password"
      
.box
  %p      
  %h3 Forgot your login ID?
  =form_tag forgot_username_url, :class => 'MainForm' do
    %label{"for"=>"email"}=:enter_your_email_address.l+":"
    = text_field_tag 'email', nil, :size => 35
    %p
      = submit_tag :send_me_my_username.l

app/views/shared/_scripts_and_styles.html.haml
=stylesheet_link_tag 'application'
=javascript_include_tag 'community_engine'
=javascript_include_tag "application"


-if  (controller_name == 'games' && action_name == 'index')
  %script
    $(function() { $(document).tooltip(); });

  %style
    label { display: inline-block; width: 5em;}

  -#=stylesheet_link_tag "event_calendar"
  -#=stylesheet_link_tag "prototip"
  -#=javascript_include_tag "event_calendar"

-if  (controller_name == 'memberships')
  -#=stylesheet_link_tag "prototip"


- if forum_page?
  -#= javascript_include_tag 'lowpro', 'forum', :plugin => 'community_engine'
  -#= stylesheet_link_tag 'infrno_forum'
  - unless @feed_icons.blank?
    - @feed_icons.each do |feed|
      = auto_discovery_link_tag :rss, feed[:url], :title => "Subscribe to '#{feed[:title]}'"
      
-if DEPLOY_GOOGLE_ANALYTICS
  %script{:type => "text/javascript"}
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-19974708-1']);
    _gaq.push(['_trackPageview']);
    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  
-if DEPLOY_QUANTCAST  
  /Quantcast
  %script{:type => "text/javascript"}
    _qoptions={
    qacct:"p-e1gHHNOLaiyLw"
    };
  %script{:type => "text/javascript", :src => "http://edge.quantserve.com/quant.js"}
  %noscript
    =image_tag("http://pixel.quantserve.com/pixel/p-e1gHHNOLaiyLw.gif", :style => "display: none;", :border => "0", :height => "1", :width => "1", :alt => "Quantcast")
  /END Quantcast  

app/views/shared/_scrollback.html.haml
%script{:type => "text/javascript"}
  window.scrollback = {"nick":"#{nick}","room":"infrno","form":"toast","minimize":true};
  (function(d,s,h,e){e=d.createElement(s);e.async=1;e.src=(location.protocol === "https:" ? "https:" : "http:") + "//scrollback.io/client.min.js";d.getElementsByTagName(s)[0].parentNode.appendChild(e);}(document,"script"));

app/views/shared/_user_admin_sidebar.html.haml
- if logged_in? && (current_user.admin? || current_user.user_admin?)
  .box
    %h3="User Admin"
    %ul
      %li= link_to( "#{:delete_this_user.l}", user_path(@user), {:method => :delete, data: {confirm: "Deleting a user can not be undone. Are you sure?"} } )
      %li= "created at: #{@user.created_at.strftime('%a, %b %d, %Y')}"
      %li= "activated at: #{@user.activated_at.strftime('%a, %b %d, %Y')}"
      -if @user.last_request_at
        %li= "last request at: #{@user.last_request_at.strftime('%a, %b %d, %Y')}"
      -else
        %li= "last request at: NIL"
      %li= "email: #{@user.email}"
      -if current_user && current_user.admin?
        =render :partial=>'users/authorizations', :locals => {:user => user}
      %li= "#{@user.login_count} logins"
      %li= "#{@user.posts.size} blog posts"
      %li= "#{@user.games.size} games"
      %li= "#{@user.characters.size} characters"
      %li= "#{@user.friendships.size} friends"
      %li= "#{@user.comments.size} comments"
      %li= "#{@user.activities_count} activities"
      %li= "#{@user.sb_posts_count} forum posts"