config/routes.rb
Crit::Application.routes.draw do

  mount CommunityEngine::Engine => "/"

  #get  '/' => 'base#site_index', :as => :home

  resources :achievements
  resources :player_registrations
  resources :intake_survey
  resources :game_systems
  resources :properties
  resources :characters
  resources :games
  resources :events do
    resources :slots
  end
  resources :characters
  resources :products
  resources :system_categories

  post '/logout' => 'sessions#destroy', :as => :logout_button

  get  '/game_systems/:id/migrate/:system_category_id' => 'game_systems#migrate', :as => :game_system_migrate
  get  '/system_categories/search/:game_system_id' => 'system_categories#index', :as => :system_category_search
  get  '/system_categories/new_game' => 'system_categories#new_game', :as => :system_categories_new_game


  get  '/system_categories/:id/pick_profile_photo' => 'system_categories#pick_profile_photo', :as => :system_category_pick_profile_photo
  put  '/system_categories/:id/change_profile_photo' => 'system_categories#change_profile_photo', :as => :system_category_change_profile_photo
  get  '/system_categories/:id/bump_views' => 'system_categories#bump_views', :as => :system_category_bump_views
  get  '/system_categories/:id/product/search' => 'system_categories#product_search', :as => :system_category_product_search
  get  '/system_categories/:id/product/:product_id/add' => 'system_categories#product_add', :as => :system_category_product_add
  get  '/system_categories/:id/product/:product_id/remove' => 'system_categories#product_remove', :as => :system_category_product_remove
  get  '/system_categories/:id/game/:game_id/add' => 'system_categories#add_game', :as => :system_category_add_game
  get  '/system_categories/:id/character/:character_id/add' => 'system_categories#add_character', :as => :system_category_add_character
  put  '/system_categories/:id/update_views' => 'system_categories#update_views', :as => :system_category_update_views
  put  '/system_categories/:id/remove_profile_photo' => 'system_categories#remove_profile_photo', :as => :system_category_remove_profile_photo

  get  '/products/:id/system_categories' => 'products#system_categories', :as => :product_system_categories

  post '/ipn_subscription_notifications' => 'ipn_subscription_notifications#create', :as => :ipn_subscription_notifications
  post '/ipn_invoice_notifications' => 'ipn_invoice_notifications#create', :as => :ipn_invoice_notifications

  get  '/membership/premium_plans' => 'memberships#premium_membership', :as => :premium_membership
  get  '/membership/mythic' => 'memberships#mythic', :as => :mythic
  get  '/membership/thank_you' => 'memberships#thank_you', :as => :membership_thank_you
  get  '/membership/discounts' => 'memberships#discounts', :as => :membership_discounts
  get  '/users/:id/membership' => 'users#membership', :as => :user_membership

  get  '/flgs' => 'base#flgs'

  get  '/users/:user_id/games/:id' => 'games#show', :as => :user_game
  get  '/users/:user_id/characters/:id' => 'characters#show', :as => :user_character
  get  '/users/:user_id/events/:id' => 'events#show', :as => :user_event

  get  '/newsletter_user_list.:format' => 'users#newsletter_user_list'
  get  '/newsletter_admin_list.:format' => 'users#newsletter_admin_list'
  get  '/newsletter_power_user_list.:format' => 'users#newsletter_power_user_list'
  get  '/newsletter_publisher_list.:format' => 'users#newsletter_publisher_list'

  get  '/users/sideload' => 'users#sideload', :as => :sideload_user

  put  '/users/:id/change_profile_photo' => 'users#change_profile_photo', :as => :user_change_profile_photo
  put  '/users/:id/update_views' => 'users#update_views', :as => :user_update_views
  get  '/users/:id/grant_network_god_mode_access' => 'users#grant_network_god_mode_access', :as => :grant_network_god_mode_access
  get  '/users/:id/revoke_network_god_mode_access' => 'users#revoke_network_god_mode_access', :as => :revoke_network_god_mode_access
  get  '/users/:id/grant_event_admin' => 'users#grant_event_admin', :as => :grant_event_admin
  get  '/users/:id/revoke_event_admin' => 'users#revoke_event_admin', :as => :revoke_event_admin
  get  '/users/:id/grant_chat_admin' => 'users#grant_chat_admin', :as => :grant_chat_admin
  get  '/users/:id/revoke_chat_admin' => 'users#revoke_chat_admin', :as => :revoke_chat_admin
  get  '/users/:id/grant_user_admin' => 'users#grant_user_admin', :as => :grant_user_admin
  get  '/users/:id/revoke_user_admin' => 'users#revoke_user_admin', :as => :revoke_user_admin
  get  '/users/:id/grant_achievement_admin' => 'users#grant_achievement_admin', :as => :grant_achievement_admin
  get  '/users/:id/revoke_achievement_admin' => 'users#revoke_achievement_admin', :as => :revoke_achievement_admin
  get  '/users/:id/ban_user' => 'users#ban_user', :as => :ban_user
  get  '/users/:id/unban_user' => 'users#unban_user', :as => :unban_user
  get  '/users/:id/address' => 'addresses#show', :as => :user_address
  get  '/users/:id/address/update' => 'addresses#update', :as => :update_user_address
  get  '/users/:id/tshirt_details' => 'users#tshirt_details', :as => :user_tshirt_details
  get  '/users/:id/tshirt_details/update' => 'users#update_tshirt_details', :as => :update_user_tshirt_details

  get  '/users/:id/grant_epic' => 'users#grant_epic', :as => :grant_epic
  get  '/users/:id/grant_legendary' => 'users#grant_legendary', :as => :grant_legendary
  get  '/users/:id/grant_exalted' => 'users#grant_exalted', :as => :grant_exalted
  get  '/users/:id/grant_mythic' => 'users#grant_mythic', :as => :grant_mythic
  get  '/users/:id/revoke_premium' => 'users#revoke_premium', :as => :revoke_premium

  get  '/games/:id/unlocked_achievements' => 'achievements#unlocked_game', :as => :unlocked_game_achievements
  get  '/characters/:id/unlocked_achievements' => 'achievements#unlocked_character', :as => :unlocked_character_achievements
  get  '/users/:id/unlocked_achievements' => 'achievements#unlocked_user', :as => :unlocked_user_achievements
  get  '/users/:id/authored_achievements' => 'achievements#authored', :as => :authored_achievements
  get  '/users/:id/achievements/manage' => 'achievements#manage', :as => :manage_achievements
  get  '/users/:id/achievements/select' => 'achievements#select_user', :as => :select_user_achievements
  get  '/games/:id/achievements/select' => 'achievements#select_game', :as => :select_game_achievements
  get  '/characters/:id/achievements/select' => 'achievements#select_character', :as => :select_character_achievements

  get  '/achievement/leaderboard/top_by_level' => 'achievements#leaderboard_top_by_level', :as => :achievement_leaderboard_top_by_level
  get  '/achievement/leaderboard/top_by_count' => 'achievements#leaderboard_top_by_count', :as => :achievement_leaderboard_top_by_count
  get  '/achievement/leaderboard/top_authors' => 'achievements#leaderboard_top_authors', :as => :achievement_leaderboard_top_authors
  get  '/achievements/:id/grant/:recipient_type/:recipient_id' => 'achievements#grant', :as => :grant_achievement
  get  '/achievements/:id/revoke/:ua_id' => 'achievements#revoke', :as => :revoke_achievement
  get  '/achievements/:id/remove/:ua_id' => 'achievements#remove', :as => :remove_achievement
  get  '/achievements/:id/accept/:ua_id' => 'achievements#accept', :as => :accept_achievement
  get  '/achievements/:id/deny/:ua_id' => 'achievements#deny', :as => :deny_achievement

  get  '/users/:id/calendar/:year/:month' => 'users#calendar', :year => Time.zone.now.year, :month => Time.zone.now.month, :as => :user_calendar
  get  '/users/:id/characters' => 'users#characters', :as => :user_characters
  get  '/users/:id/games' => 'users#games', :as => :user_games
  get  '/users/:id/games_playing' => 'users#games_playing', :as => :user_games_playing

  put  '/characters/:id/update_views' => 'characters#update_views', :as => :character_update_views
  get  '/characters/:id/pick_profile_photo' => 'characters#pick_profile_photo', :as => :character_pick_profile_photo
  put  '/characters/:id/change_profile_photo' => 'characters#change_profile_photo', :as => :character_change_profile_photo
  get  '/characters/:id/new_avatar_photo' => 'characters#new_avatar_photo', :as => :new_character_avatar_photo
  get  '/characters/:id/game_table_sheet' => 'characters#game_table_sheet', :as => :game_table_sheet
  get  '/characters/:id/edit_clone' => 'characters#edit_clone', :as => :edit_character_clone
  get  '/characters/:id/sheet' => 'characters#sheet', :as => :sheet
  get  '/characters/:id/print' => 'characters#print'
  get  '/characters/:id/posts' => 'posts#character_index', :as => :character_post
  get  '/characters/:id/notepad' => 'characters#notepad', :as => :character_notepad
  get  '/characters/:id/edit_notepad' => 'characters#edit_notepad', :as => :character_edit_notepad
  patch  '/characters/:id/update_notepad' => 'characters#update_notepad', :as => :character_update_notepad
  get  '/characters/auto_complete_for_character_genre' => 'characters#auto_complete_for_character_genre', :as => :auto_complete_for_character_genre

  get  '/characters/:id/products/' => 'characters#products', :as => :character_products
  #get  '/characters/:id/product/search' => 'characters#product_search', :as => :character_product_search
  get  '/characters/:id/product/:product_id/add' => 'characters#product_add', :as => :character_product_add
  get  '/characters/:id/product/:product_id/remove' => 'characters#product_remove', :as => :character_product_remove

  put  '/games/:id/update_views' => 'games#update_views', :as => :game_update_views
  put  '/games/:id/change_profile_photo' => 'games#change_profile_photo', :as => :game_change_profile_photo
  get  '/games/:id/register_player_for_event/slot/:slot_id' => 'games#register_player_for_event', :as => :register_player_for_event
  get  '/games/:id/register_alternate_for_event/slot/:slot_id' => 'games#register_alternate_for_event', :as => :register_alternate_for_event

app/controllers/tags_controller.rb
class TagsController < BaseController
  require_from_ce('controllers/tags_controller')

  before_filter :login_required, :only => [:manage, :edit, :update, :destroy]
  before_filter :admin_required, :only => [:manage, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => 'auto_complete_for_tag_name'
  #
  #caches_action :show, :cache_path => Proc.new { |controller| controller.send(:tag_url, controller.params[:id]) }, :if => Proc.new{|c| c.cache_action? }
  #def cache_action?
  #  !logged_in? && params[:type].blank?
  #end

  #def auto_complete_for_tag_name
  #  #if !params[:id].blank? || !params[:tag_list].blank?
  #    #@tags = ActsAsTaggableOn::Tag.find(:all, :limit => 10, :conditions => [ 'LOWER(name) LIKE ?', '%' + (params[:id] || params[:tag_list]) + '%' ])
  #    #@tags = Tag.all(:conditions => [ 'LOWER(name) LIKE ?', '%' + (params[:id] || params[:tag_list]) + '%' ])
  #
  #    @tags = ActsAsTaggableOn::Tag.find(:all, :limit => 10, :conditions => [ 'LOWER(name) LIKE ?', '%' + (params[:id] || params[:tag_list]) + '%' ])
  #    render :inline => "<%= infrno_auto_complete_result(@tags, 'name') %>"
  #
  #
  #end

  
  def index  
    @tags = popular_tags(500).to_a
    #@character_tags = popular_tags(75, 'Character').to_a
    #@product_tags = popular_tags(75, 'Product').to_a
    #@game_tags = popular_tags(75, 'Game').to_a
    #@user_tags = popular_tags(75, 'User').to_a
    #@post_tags = popular_tags(75, 'Post').to_a
    #@photo_tags = popular_tags(75, 'Photo').to_a
    #@clipping_tags = popular_tags(75, 'Clipping').to_a
  end
  
  def show
    tag_array = ActsAsTaggableOn::TagList.from( URI::decode(params[:id]) )

    @tags = ActsAsTaggableOn::Tag.where('name IN (?)', tag_array)
    if @tags.nil? || @tags.empty?
      flash[:notice] = :tag_does_not_exists.l_with_args(:tag => tag_array)
      redirect_to :action => :index and return
    end

    @related_tags = @tags.first.related_tags
    @tags_raw = @tags.collect { |t| t.name } .join(',')
    @popular_tags = popular_tags(50)

    if params[:type]
      case params[:type]
        when 'Product', 'product'
          @products = @products = Product.recent.tagged_with(tag_array).page(params[:page]).per(30)
          @characters, @games, @posts, @photos, @users, @clippings = [], [], [], [], [], []
        when 'Character', 'character'
          @characters = @characters = Character.recent.tagged_with(tag_array).page(params[:page]).per(30)
          @products, @games, @posts, @photos, @users, @clippings = [], [], [], [], [], []
        when 'Game', 'games'
          @games = @games = Game.recent.tagged_with(tag_array).page(params[:page]).per(30)
          @products, @characters, @posts, @photos, @users, @clippings = [], [], [], [], [], []
        when 'Post', 'posts'
          @pages = @posts = Post.recent.tagged_with(tag_array).page(params[:page]).per(30)
          @products, @characters, @games, @photos, @users, @clippings = [], [], [], [], [], []
        when 'Photo', 'photos'
          @pages = @photos = Photo.recent.tagged_with(tag_array).page(params[:page]).per(30)
          @products, @characters, @games, @posts, @users, @clippings = [], [], [], [], [], []
        when 'User', 'users'
          @pages = @users = User.recent.tagged_with(tag_array).page(params[:page]).per(30)
          @products, @characters, @games, @posts, @photos, @clippings = [], [], [], [], [], []
        when 'Clipping', 'clippings'
          @pages = @clippings = Clipping.recent.tagged_with(tag_array).page(params[:page]).per(30)
          @products, @characters, @games, @posts, @photos, @users = [], [], [], [], []
      else
        @products, @characters, @games, @clippings, @posts, @photos, @users = [], [], [], [], [], [], []
      end
    else
      @products = Product.recent.limit(5).tagged_with(tag_array)
      @characters = Character.limit(5).tagged_with(tag_array)
      @games = Game.recent.limit(5).tagged_with(tag_array)
      @posts = Post.recent.limit(5).tagged_with(tag_array)
      @photos = Photo.recent.limit(5).tagged_with(tag_array)
      @users = User.recent.limit(5).tagged_with(tag_array).uniq
      #@clippings = Clipping.recent.limit(5).tagged_with(tag_array)
    end

    respond_to do |format|
      format.all { render "show.html.haml" }
    end

  end

end

app/views/tags/_tags.html.haml
.box
  %h3
    Tags,
    =link_to 'see all', tags_path
    %p
    -tag_cloud @popular_tags, %w(css1 css2 css3 css4) do |tag, css_class|
      =link_to tag.name, tag_url(tag.to_param), :class => css_class

app/views/tags/index.html.haml
#col1

  -box :class => "alt" do
    %h3 Search by tag
    %form.MainForm{"action"=>"/search/tags/", "method"=>"get"}
      = text_field_tag 'id', params[:id], :autocomplete => "off"
      -##id_auto_complete.auto_complete{"class"=>"auto_complete", "id"=>"id_auto_complete"}
      -#= auto_complete_field 'id', {:url => { :controller => "tags", :action => 'auto_complete_for_tag_name'}, :tokens => [','] }
      %p
        %input{"type"=>"submit", "value"=>:go.l}

  =render :partial => "shared/ad"

#col2
  -box :class => "yui-b" do
    %h3= :browse_content_by_tags.l
    - tag_cloud @tags, %w(nube1 nube2 nube3 nube4 nube5) do |name, css_class|
      =link_to h(name), tag_url(URI.escape(name.to_s, /[\/.?#]/)), :class => css_class

app/views/tags/show.html.haml
#col1
  -box :class => "alt first_alt" do 
    %h3
      - if params[:type]
        = (params[:type].pluralize + ' tagged').l
      - else
        = :items_tagged.l
      - @tags.each do |tag|
        = link_to h(tag.name), tag_path(tag.name)
     
  -#=render :partial => "shared/ad"
  -#
  -#-if @related_tags
  -#  .box
  -#    %h3
  -#      Related tags,
  -#      = link_to 'see all', tags_path
  -#    %ul
  -#      -tag_cloud @related_tags, %w(css1 css2 css3 css4) do |tag, css_class|
  -#        =link_to h(tag.name), tag_path(tag), :class => css_class
  -#
  -#=render :partial => "shared/ad"
  -#
  -#-if @popular_tags
  -#  .box
  -#    %h3
  -#      Popular tags,
  -#      = link_to 'see all', tags_path
  -#    %ul
  -#      - tag_cloud @popular_tags, %w(nube1 nube2 nube3 nube4 nube5) do |name, css_class|
  -#        - css_class = css_class + (name.eql?(params[:id]) ? " selected": "")
  -#        %li.tags= link_to name, tag_url(u name.name), :class => css_class
    
  =render :partial => "shared/ad"

#col2
  - if @games.any?
    .box
      %h3
        Games 
        - unless params[:type]
          = " : " 
          =link_to "All games tagged #{ @tags_raw }", show_tag_type_path(:id => @tags_raw, :type => 'Game').html_safe
      - @games.each do |game|
        =render :partial => "games/game_listing", :locals => {:game => game} 
      
  - if @characters.any?
    .box
      %h3 
        Characters
        - unless params[:type]
          = " : " 
          = link_to "All characters tagged #{ @tags_raw }", show_tag_type_path(:id => @tags_raw, :type => 'Character').html_safe
      - @characters.each do |character|
        =render :partial => "characters/character_listing", :locals => {:character => character} 

  - if @posts.any?
    .box
      %h3
        Posts
        - unless params[:type]
          = " : " 
          = link_to "All posts tagged #{ @tags_raw }", show_tag_type_path(:id => @tags_raw, :type => 'Post').html_safe

      = render :partial => 'posts/post', :collection => @posts      

  - if @photos.any?
    .box
      %h3
        =:photos.l(:count => @photos.size)
        - unless params[:type]
          = " : " 
          = link_to :all_photos_tagged.l(:tag_name => @tags_raw ), show_tag_type_path(:id => @tags_raw, :type => 'Photo').html_safe
      - @photos.each do |photo|
        = link_to image_tag(photo.photo.url(:thumb), :title => "#{photo.description} ("+:uploaded_by.l+" #{photo.user.login})", :class => "polaroid"), user_photo_path(photo.user, photo)
        
  - if @users.any?
    .box
      %h3
        Users
        - unless params[:type]
          = " : " 
          = link_to :all_users_tagged.l(:tag_name => @tags_raw ), show_tag_type_path(:id => @tags_raw, :type => 'User').html_safe
      - @users.each do |user|
        =render :partial => "users/user", :locals => {:user => user} 

  /- if @products.any?
  /  .box
  /    %h3
  /      Products
  /      - unless params[:type]
  /        = " : "
  /        = link_to "All products tagged #{ @tags_raw }", show_tag_type_path(:id => @tags_raw, :type => 'Product').html_safe
  /    - @products.each do |product|
  /      =render :partial => "products/product", :locals => {:product => product}


  /- unless @clippings.empty?
  /  .box
  /    %h3= :clippings.l
  /    - @clippings.each do |clipping|
  /      %a{"href"=>"#{h user_clipping_url(clipping.user, clipping) }"}
  /        %img.polaroid.clipping{"src"=>"#{h clipping.image_uri}", "style"=>"width:108px"}
  /    %h6.all= link_to :all_clippings_tagged.l(:tag_name =>  h(@tags_raw) ), show_tag_type_path(:id => @tags_raw, :type => 'Clipping') unless params[:type]